coll3<-read.table('collection_3.txt')
write.table(t(coll3),'collection_3_t.txt',col.names=F,row.names=F)
coll4<-read.table('collection_4.txt')
write.table(t(coll4),'collection_4_t.txt',col.names=F,row.names=F)
coll5<-read.table('collection_5.txt')
write.table(t(coll5),'collection_5_t.txt',col.names=F,row.names=F)

coll3<-read.table('collection_3.txt')
write.table(t(coll3)[,-(1:250)],'collection_3_tshort.txt',col.names=F,row.names=F)
coll4<-read.table('collection_4.txt')
write.table(t(coll4)[,-(1:250)],'collection_4_tshort.txt',col.names=F,row.names=F)
coll5<-read.table('collection_5.txt')
write.table(t(coll5)[,-(1:250)],'collection_5_tshort.txt',col.names=F,row.names=F)

range(coll3)
range(coll4)
range(coll5)